services:
  postgres:
    image: postgres:15  
    container_name: pg-auth
    hostname: postgres
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  
    networks:
      app-network:
        aliases:
          - postgres  
    restart: unless-stopped

  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: cloud-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud
      SPRING_DATASOURCE_USERNAME: cloud
      SPRING_DATASOURCE_PASSWORD: cloud
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: 30000
    networks:
      - app-network
    restart: unless-stopped

  map:
    image: maptiler/tileserver-gl:latest
    container_name: osm-map
    ports:
      - "8081:8080"
    volumes:
      - ./map:/data:ro
    environment:
      - MBTILES_FILE=maptiler-osm-2020-02-10-v3.11-madagascar_antananarivo.mbtiles
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  pgdata: