services:

  postgres:
    image: postgres:latest
    container_name: pg-auth
    environment:
      POSTGRES_DB: cloud
      POSTGRES_USER: cloud
      POSTGRES_PASSWORD: cloud
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql  # Chang√© ici
    restart: unless-stopped

  api:
    build:
      context: ./app
    container_name: cloud-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud
      SPRING_DATASOURCE_USERNAME: cloud
      SPRING_DATASOURCE_PASSWORD: cloud
    restart: unless-stopped

  map:
    image: overv/openstreetmap-tile-server
    container_name: osm-map
    command: run 
    ports:
      - "8081:80"
    volumes:
      - ./map/data:/data
    environment:
      - UPDATES=disabled
    restart: unless-stopped

volumes:
  pgdata: